app_name = "gin_test"
app_version = 1.0

[dhb_common]
host = "localhost"
port = "3306"
user = "root"
password = ""
dbname = "dhb_common"

[dbb_data]
host = "localhost"
port = "3306"
user = "root"
password = ""
dbname = "dhb_data_1"

[db_gin_test]
host = "localhost"
port = "3306"
user = "root"
password = ""
dbname = "gin_test"

[log]
log_debug_mode = true
log_format = "%{color}%{time:2006/01/02 15:04:05 -07:00 MST} [%{level:.6s}] %{shortfile} : %{color:reset}%{message}"